### ISSUE TITLE
auto allocate 选择true时 只有一个线程可取值

### ISSUE THREAD

**Issue by zhangzhaox** [rollno748/Extended-csv-dataset-config#1]
![image](https://user-images.githubusercontent.com/82088551/164887168-d4248d1e-7a46-43ca-9735-477bac027b84.png)
![image](https://user-images.githubusercontent.com/82088551/164887216-77f8e909-d0ad-4aae-be6a-32076159c191.png)

**Comment by rollno748** [comment]
Hello Thanks again for bringing this up.

This issue is replicated in mine - I will work on it and provide the fix at the earliest.

![image](https://user-images.githubusercontent.com/18440913/164889412-99df689d-83c3-4635-b2b7-66490e7b40da.png)

![image](https://user-images.githubusercontent.com/18440913/164889422-6f477030-304a-406a-a1c6-ef23e3565f2c.png)

I see that the Thread one over reading it from its block size - Ideally thread1 has to read only between 0-4 and thread2 between 5-9 but here thread2 is working fine but not thread1

![image](https://user-images.githubusercontent.com/18440913/164889547-d3116192-cefd-4244-9116-8a75fd2e40d3.png)


I am on it - will fix and push the patch - Thanks again for reporting

**Comment by rollno748** [comment]
I have pushed a patch  - please download the version 1.1 and validate.
https://github.com/rollno748/Extended-csv-dataset-config/releases/download/1.1/di-extended-csv-1.1.jar

I will close this issue upon your confirmation. Thanks
